version: '3'

services: 


  nginx-service:
    build: 
      context: .
      dockerfile: ./Dockerfile2
    container_name: nginx-container
    ports: 
      - "8080:80"
    depends_on:
      - php-service
      - mysql-service
  
  
  php-service:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-container
    ports: 
      - "9000:9000"
   
    
  mysql-service:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: mysql-container
    ports:
            - "3306:3306"
    restart: on-failure 
    environment:
      MYSQL_DATABASE: graphqlexample
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%" 

##Conteneur Adminer pour gérer la BD avec une interface graphique 
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8081:8080
  
 #Conteneur node pour servir l'application Angular 
  node:
    build:
      context: .
      dockerfile: ./graphqlfront2/Dockerfile
    container_name: angular_node
    ports:
      - 4200:4200
    tty: true
    command:
      - /bin/sh
      - -c
      - |
          cd /home/node/app/frontend && npm start
