version: '3'

services: 


  nginx-service:

    image: nginx:stable-alpine 
    container_name: nginx-container
    ports: 
      - "8080:80"
    volumes: 
      - ./graphqlexample:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
  
  
  php-service:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-container
    ports: 
      - "9000:9000"
    volumes: 
      - ./graphqlexample:/var/www/project
    
  mysql-service:
    image: mysql:8
    container_name: mysql-container
    ports:
            - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure 
    environment:
      MYSQL_DATABASE: graphqlexample
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    

##Conteneur Adminer pour gérer la BD avec une interface graphique 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  
 #Conteneur node pour servir l'application Angular 
  node:
    build: ./graphqlfront2
    container_name: angular_node
    ports:
      - 4200:4200
    volumes:
      - ./graphqlfront2:/home/node/app/frontend
    tty: true
    command:
      - /bin/sh
      - -c
      - |
          cd /home/node/app/frontend && npm start
