apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - name: mysql
        image: alazouari/mysql